# Generated by Django 5.0.4 on 2024-09-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0014_alter_booking_id_alter_category_id_alter_checkin_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='details',
            field=models.TextField(default='Wi-Fi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AddField(
            model_name='room',
            name='special_facilities',
            field=models.ManyToManyField(to='hotel_app.facility'),
        ),
    ]
