# Generated by Django 5.0.4 on 2024-09-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0015_facility_room_details_alter_room_price_per_night_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='meals_included',
            field=models.BooleanField(default=False),
        ),
    ]
