# Generated by Django 5.0.4 on 2024-09-27 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0016_room_meals_included'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer',
        ),
        migrations.AddField(
            model_name='checkout',
            name='booking',
            field=models.OneToOneField(default='22', on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='hotel_app.booking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
